name: hello_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  google_maps_flutter: ^2.2.3

  flutter_polyline_points: ^2.1.0
  geolocator: ^12.0.0

  file_picker: ^8.0.0  
  google_fonts: ^4.0.4  
  audioplayers: ^6.1.0
  image_picker: ^1.0.7
  http: ^1.2.2
  google_maps_widget: ^1.0.6
  flutter_spinkit: ^5.2.2
  google_place: ^0.4.7
  flutter_google_places_sdk: ^0.3.0
  permission_handler: ^11.0.1

dependency_overrides:
  http: ^0.13.6


dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^6.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/music/alarm.mp3
    - assets/audio/

  fonts:
    - family: Grillin
      fonts:
        - asset: assets/fonts/Grillin.otf
    - family: Reselu
      fonts:
        - asset: assets/fonts/Reselu.ttf
    - family: Cangkang
      fonts:
        - asset: assets/fonts/CangKang.otf
    - family: Gerdu
      fonts:
        - asset: assets/fonts/Gerdu.otf