name: hello_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  cupertino_icons: ^1.0.8
  

  google_maps_flutter: ^2.2.3
  flutter_polyline_points: ^3.0.1
  geolocator: ^14.0.2


  file_picker: ^10.3.3
  google_fonts: ^6.3.1
  audioplayers: ^6.1.0
  image_picker: ^1.0.7
  http: ^1.2.2
  google_maps_widget: ^1.0.6
  flutter_spinkit: ^5.2.2
  google_place: ^0.4.7


  flutter_google_places_sdk: ^0.4.2+1
  permission_handler: ^12.0.1
  avatar_glow: ^3.0.1
  flutter_sound: ^9.2.13
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3
  url_launcher: ^6.3.1
  google_sign_in: ^6.2.1
  firebase_database: 12.0.1
  cached_network_image: ^3.3.1
  shimmer: ^2.0.0
  flutter_slidable: ^3.0.1
  intl: ^0.18.1
  path: ^1.8.0
  shared_preferences: ^2.2.2
  firebase_storage: ^13.0.1
  path_provider: ^2.1.1
  lottie: ^2.0.0
  location: ^7.0.0
  record: ^6.1.1
  rxdart: ^0.27.7
  flutter_compass: ^0.8.0


dependency_overrides:
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/music/alarm.mp3
    - assets/audio/
    - assets/images/profile_placeholder.png

  fonts:
    - family: Grillin
      fonts:
        - asset: assets/fonts/Grillin.otf
    - family: Reselu
      fonts:
        - asset: assets/fonts/Reselu.ttf
    - family: Cangkang
      fonts:
        - asset: assets/fonts/CangKang.otf
    - family: Gerdu
      fonts:
        - asset: assets/fonts/Gerdu.otf