// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRaQhQUz89nLbF6uPags0yiqyrEwcofPw',
    appId: '1:74119039138:web:bca111fa6b888977e42ffb',
    messagingSenderId: '74119039138',
    projectId: 'utmbright',
    authDomain: 'utmbright.firebaseapp.com',
    storageBucket: 'utmbright.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-_nt443AWlwCb56RKZyK_HLVhDpP6hyw',
    appId: '1:74119039138:android:9fcd0e8ebf542cf8e42ffb',
    messagingSenderId: '74119039138',
    projectId: 'utmbright',
    storageBucket: 'utmbright.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz6v4IGOfMfhXQG11_OAsV17ofye8icF0',
    appId: '1:74119039138:ios:a541991135b1391ee42ffb',
    messagingSenderId: '74119039138',
    projectId: 'utmbright',
    storageBucket: 'utmbright.firebasestorage.app',
    iosBundleId: 'com.example.helloFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRaQhQUz89nLbF6uPags0yiqyrEwcofPw',
    appId: '1:74119039138:web:56808ddb7d069befe42ffb',
    messagingSenderId: '74119039138',
    projectId: 'utmbright',
    authDomain: 'utmbright.firebaseapp.com',
    storageBucket: 'utmbright.firebasestorage.app',
  );
}
