// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMAuyquC_htfp_w5Q1n-NA1Hg3ccBeXeU',
    appId: '1:144599433533:android:f0e53b10591d16a9290554',
    messagingSenderId: '144599433533',
    projectId: 'utmbright-56819',
    databaseURL: 'https://utmbright-56819-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'utmbright-56819.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv4N37yQn6tb1AfN-ABL2Phh1BxLgkjw4',
    appId: '1:144599433533:ios:3411e46191bf2217290554',
    messagingSenderId: '144599433533',
    projectId: 'utmbright-56819',
    databaseURL: 'https://utmbright-56819-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'utmbright-56819.firebasestorage.app',
    iosBundleId: 'com.example.helloFlutter',
  );
}
